apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-translate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-translate
  template:
    metadata:
      labels:
        app: flask-translate
    spec:
      containers:
      - name: flask-translate
        image: flask-translate:latest  # Image đã build
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-translate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort  # Expose ra ngoài Minikube
